name:  boringman
title:   Boring Man
version: "1.2.7.2"
summary:   Battle other badly drawn 2D stickman online while jumping around like a lunatic
description: |
  Battle other badly drawn 2D stickman online while jumping around like a lunatic and getting blown up into smithereens. With over 50 weapons, Boring Man is the most chaotic and hilarious 2D online shooter on the internet. Customize game modes with highly flexible options and crazy mutators, go online with or against your friends to reign supreme on the battlefield, fight against a zombie horde, or maybe challenge your platforming skills in devastatingly difficult climbing maps. Create your own maps to share with your friends and enemies. In Boring Man, it's everything but boring.

grade: stable
icon: boringman_icon.png

base: core18
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386

environment:
  WINEDLLOVERRIDES: "$WINEDLLOVERRIDES;mscoree,mshtml="    # Prevent pop-ups about Wine Mono and Wine Gecko
  SOMMELIER_STRICT: "1"                                    # Make Sommelier exit when unset variable is used. (useful to find bugs in sommelier)

apps:
  boringman:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "Joust3_RevengeOfTheLavaTroll.exe"
      #INSTALL_EXE: "$SNAP/Blockout25_setup.exe"
      #INSTALL_FLAGS: "/S"
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - cups
  # The wine command can be used to run applications inside the wine
  # environment that this snap uses.
  #
  # For example, users can configure the wine environment of this snap
  # by running `myapp.wine winecfg`.
  wine:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - cups
 # The winetricks command can be used to run winetricks inside the wine
  # environment that this snap uses.
  winetricks:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  installer:
    plugin: dump
    source: ./

  # The sommelier script helps you snap Windows applications using Wine. It 
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git

# These plugs are used to connect the snap to the wine runtime.
plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-5-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-5-stable

